// Code generated by protoc-gen-go. DO NOT EDIT.
// source: modelRunner.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoadModelMessage struct {
	ModelName            string   `protobuf:"bytes,1,opt,name=ModelName,proto3" json:"ModelName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadModelMessage) Reset()         { *m = LoadModelMessage{} }
func (m *LoadModelMessage) String() string { return proto.CompactTextString(m) }
func (*LoadModelMessage) ProtoMessage()    {}
func (*LoadModelMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0263680330d05492, []int{0}
}

func (m *LoadModelMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadModelMessage.Unmarshal(m, b)
}
func (m *LoadModelMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadModelMessage.Marshal(b, m, deterministic)
}
func (m *LoadModelMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadModelMessage.Merge(m, src)
}
func (m *LoadModelMessage) XXX_Size() int {
	return xxx_messageInfo_LoadModelMessage.Size(m)
}
func (m *LoadModelMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadModelMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LoadModelMessage proto.InternalMessageInfo

func (m *LoadModelMessage) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

type RunModelMessage struct {
	ModelName string `protobuf:"bytes,1,opt,name=ModelName,proto3" json:"ModelName,omitempty"`
	// TODO - Change this to correct object for observations
	Input                string   `protobuf:"bytes,2,opt,name=Input,proto3" json:"Input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunModelMessage) Reset()         { *m = RunModelMessage{} }
func (m *RunModelMessage) String() string { return proto.CompactTextString(m) }
func (*RunModelMessage) ProtoMessage()    {}
func (*RunModelMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0263680330d05492, []int{1}
}

func (m *RunModelMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunModelMessage.Unmarshal(m, b)
}
func (m *RunModelMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunModelMessage.Marshal(b, m, deterministic)
}
func (m *RunModelMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunModelMessage.Merge(m, src)
}
func (m *RunModelMessage) XXX_Size() int {
	return xxx_messageInfo_RunModelMessage.Size(m)
}
func (m *RunModelMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RunModelMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RunModelMessage proto.InternalMessageInfo

func (m *RunModelMessage) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *RunModelMessage) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type ModelResultMessage struct {
	Action               string   `protobuf:"bytes,1,opt,name=Action,proto3" json:"Action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelResultMessage) Reset()         { *m = ModelResultMessage{} }
func (m *ModelResultMessage) String() string { return proto.CompactTextString(m) }
func (*ModelResultMessage) ProtoMessage()    {}
func (*ModelResultMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0263680330d05492, []int{2}
}

func (m *ModelResultMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelResultMessage.Unmarshal(m, b)
}
func (m *ModelResultMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelResultMessage.Marshal(b, m, deterministic)
}
func (m *ModelResultMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelResultMessage.Merge(m, src)
}
func (m *ModelResultMessage) XXX_Size() int {
	return xxx_messageInfo_ModelResultMessage.Size(m)
}
func (m *ModelResultMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelResultMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ModelResultMessage proto.InternalMessageInfo

func (m *ModelResultMessage) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func init() {
	proto.RegisterType((*LoadModelMessage)(nil), "pb.LoadModelMessage")
	proto.RegisterType((*RunModelMessage)(nil), "pb.RunModelMessage")
	proto.RegisterType((*ModelResultMessage)(nil), "pb.ModelResultMessage")
}

func init() { proto.RegisterFile("modelRunner.proto", fileDescriptor_0263680330d05492) }

var fileDescriptor_0263680330d05492 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0xcd, 0x4f, 0x49,
	0xcd, 0x09, 0x2a, 0xcd, 0xcb, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a,
	0x48, 0x52, 0x32, 0xe0, 0x12, 0xf0, 0xc9, 0x4f, 0x4c, 0xf1, 0x05, 0x49, 0xfa, 0xa6, 0x16, 0x17,
	0x27, 0xa6, 0xa7, 0x0a, 0xc9, 0x70, 0x71, 0x82, 0xf9, 0x7e, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x08, 0x01, 0x25, 0x57, 0x2e, 0xfe, 0xa0, 0xd2, 0x3c, 0xe2, 0x35, 0x08,
	0x89, 0x70, 0xb1, 0x7a, 0xe6, 0x15, 0x94, 0x96, 0x48, 0x30, 0x81, 0x65, 0x20, 0x1c, 0x25, 0x1d,
	0x2e, 0x21, 0xb0, 0x92, 0xa0, 0xd4, 0xe2, 0xd2, 0x9c, 0x12, 0x98, 0x49, 0x62, 0x5c, 0x6c, 0x8e,
	0xc9, 0x25, 0x99, 0xf9, 0x79, 0x50, 0x63, 0xa0, 0x3c, 0x23, 0x0f, 0x2e, 0x6e, 0x5f, 0x84, 0xfb,
	0x85, 0x2c, 0xb9, 0x38, 0x60, 0x6e, 0x10, 0x12, 0xd6, 0x2b, 0x48, 0xd2, 0x43, 0x73, 0x91, 0x94,
	0x18, 0x48, 0x10, 0xd3, 0x7c, 0x25, 0x86, 0x24, 0x36, 0xb0, 0xdf, 0x8d, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x56, 0x62, 0x64, 0x4f, 0x10, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ModelRunnerClient is the client API for ModelRunner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModelRunnerClient interface {
	// Execute something on data
	RunModel(ctx context.Context, in *RunModelMessage, opts ...grpc.CallOption) (*ModelResultMessage, error)
}

type modelRunnerClient struct {
	cc *grpc.ClientConn
}

func NewModelRunnerClient(cc *grpc.ClientConn) ModelRunnerClient {
	return &modelRunnerClient{cc}
}

func (c *modelRunnerClient) RunModel(ctx context.Context, in *RunModelMessage, opts ...grpc.CallOption) (*ModelResultMessage, error) {
	out := new(ModelResultMessage)
	err := c.cc.Invoke(ctx, "/pb.ModelRunner/RunModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelRunnerServer is the server API for ModelRunner service.
type ModelRunnerServer interface {
	// Execute something on data
	RunModel(context.Context, *RunModelMessage) (*ModelResultMessage, error)
}

func RegisterModelRunnerServer(s *grpc.Server, srv ModelRunnerServer) {
	s.RegisterService(&_ModelRunner_serviceDesc, srv)
}

func _ModelRunner_RunModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunModelMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelRunnerServer).RunModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ModelRunner/RunModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelRunnerServer).RunModel(ctx, req.(*RunModelMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _ModelRunner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ModelRunner",
	HandlerType: (*ModelRunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunModel",
			Handler:    _ModelRunner_RunModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modelRunner.proto",
}
