// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulation.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SpawnAgentMessage struct {
	X                    int32    `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpawnAgentMessage) Reset()         { *m = SpawnAgentMessage{} }
func (m *SpawnAgentMessage) String() string { return proto.CompactTextString(m) }
func (*SpawnAgentMessage) ProtoMessage()    {}
func (*SpawnAgentMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{0}
}

func (m *SpawnAgentMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpawnAgentMessage.Unmarshal(m, b)
}
func (m *SpawnAgentMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpawnAgentMessage.Marshal(b, m, deterministic)
}
func (m *SpawnAgentMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpawnAgentMessage.Merge(m, src)
}
func (m *SpawnAgentMessage) XXX_Size() int {
	return xxx_messageInfo_SpawnAgentMessage.Size(m)
}
func (m *SpawnAgentMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SpawnAgentMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SpawnAgentMessage proto.InternalMessageInfo

func (m *SpawnAgentMessage) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *SpawnAgentMessage) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type SpawnAgentResultMessage struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpawnAgentResultMessage) Reset()         { *m = SpawnAgentResultMessage{} }
func (m *SpawnAgentResultMessage) String() string { return proto.CompactTextString(m) }
func (*SpawnAgentResultMessage) ProtoMessage()    {}
func (*SpawnAgentResultMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{1}
}

func (m *SpawnAgentResultMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpawnAgentResultMessage.Unmarshal(m, b)
}
func (m *SpawnAgentResultMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpawnAgentResultMessage.Marshal(b, m, deterministic)
}
func (m *SpawnAgentResultMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpawnAgentResultMessage.Merge(m, src)
}
func (m *SpawnAgentResultMessage) XXX_Size() int {
	return xxx_messageInfo_SpawnAgentResultMessage.Size(m)
}
func (m *SpawnAgentResultMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SpawnAgentResultMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SpawnAgentResultMessage proto.InternalMessageInfo

func (m *SpawnAgentResultMessage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// TODO - implement this function
type ObserveRequestMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObserveRequestMessage) Reset()         { *m = ObserveRequestMessage{} }
func (m *ObserveRequestMessage) String() string { return proto.CompactTextString(m) }
func (*ObserveRequestMessage) ProtoMessage()    {}
func (*ObserveRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{2}
}

func (m *ObserveRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObserveRequestMessage.Unmarshal(m, b)
}
func (m *ObserveRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObserveRequestMessage.Marshal(b, m, deterministic)
}
func (m *ObserveRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObserveRequestMessage.Merge(m, src)
}
func (m *ObserveRequestMessage) XXX_Size() int {
	return xxx_messageInfo_ObserveRequestMessage.Size(m)
}
func (m *ObserveRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ObserveRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ObserveRequestMessage proto.InternalMessageInfo

type EntityUpdateMessage struct {
	Action               string   `protobuf:"bytes,1,opt,name=Action,proto3" json:"Action,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Class                string   `protobuf:"bytes,3,opt,name=Class,proto3" json:"Class,omitempty"`
	X                    int32    `protobuf:"varint,4,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int32    `protobuf:"varint,5,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityUpdateMessage) Reset()         { *m = EntityUpdateMessage{} }
func (m *EntityUpdateMessage) String() string { return proto.CompactTextString(m) }
func (*EntityUpdateMessage) ProtoMessage()    {}
func (*EntityUpdateMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{3}
}

func (m *EntityUpdateMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityUpdateMessage.Unmarshal(m, b)
}
func (m *EntityUpdateMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityUpdateMessage.Marshal(b, m, deterministic)
}
func (m *EntityUpdateMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityUpdateMessage.Merge(m, src)
}
func (m *EntityUpdateMessage) XXX_Size() int {
	return xxx_messageInfo_EntityUpdateMessage.Size(m)
}
func (m *EntityUpdateMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityUpdateMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EntityUpdateMessage proto.InternalMessageInfo

func (m *EntityUpdateMessage) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *EntityUpdateMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EntityUpdateMessage) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *EntityUpdateMessage) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *EntityUpdateMessage) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*SpawnAgentMessage)(nil), "pb.SpawnAgentMessage")
	proto.RegisterType((*SpawnAgentResultMessage)(nil), "pb.SpawnAgentResultMessage")
	proto.RegisterType((*ObserveRequestMessage)(nil), "pb.ObserveRequestMessage")
	proto.RegisterType((*EntityUpdateMessage)(nil), "pb.EntityUpdateMessage")
}

func init() { proto.RegisterFile("simulation.proto", fileDescriptor_961a558581160483) }

var fileDescriptor_961a558581160483 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4d, 0x4f, 0x83, 0x40,
	0x10, 0x86, 0xbb, 0x28, 0x35, 0x4e, 0x8c, 0xd1, 0xd1, 0x0a, 0xd6, 0x8b, 0xd9, 0x93, 0x27, 0xfc,
	0xfa, 0x05, 0x68, 0x3c, 0xf4, 0x60, 0x4c, 0x20, 0x26, 0xed, 0x71, 0x91, 0x49, 0x43, 0x82, 0xb0,
	0x76, 0x06, 0x8d, 0xbf, 0xc3, 0x3f, 0x6c, 0xf8, 0x68, 0x2b, 0x91, 0xe3, 0x0b, 0xf3, 0x4e, 0x9e,
	0x67, 0x16, 0x8e, 0x38, 0x7b, 0xaf, 0x72, 0x23, 0x59, 0x59, 0x04, 0x76, 0x55, 0x4a, 0x89, 0x8e,
	0x4d, 0xf4, 0x35, 0x1c, 0xc7, 0xd6, 0x7c, 0x15, 0xe1, 0x92, 0x0a, 0x79, 0x26, 0x66, 0xb3, 0x24,
	0x3c, 0x00, 0x35, 0xf7, 0xd5, 0xa5, 0xba, 0x72, 0x23, 0x35, 0xaf, 0xd3, 0xc2, 0x77, 0xda, 0xb4,
	0xd0, 0xb7, 0xe0, 0x6d, 0x0b, 0x11, 0x71, 0x95, 0x6f, 0x6a, 0x67, 0x30, 0x8e, 0xc5, 0x48, 0xc5,
	0x4d, 0x77, 0x3f, 0xea, 0x92, 0xf6, 0x60, 0xf2, 0x92, 0x30, 0xad, 0x3e, 0x29, 0xa2, 0x8f, 0x8a,
	0x78, 0x5d, 0xd0, 0x25, 0x9c, 0x3c, 0x15, 0x92, 0xc9, 0xf7, 0xab, 0x4d, 0x8d, 0xd0, 0x9f, 0x3d,
	0xe1, 0x5b, 0xcd, 0xb9, 0xde, 0xd3, 0x26, 0x3c, 0x04, 0x67, 0x96, 0x76, 0x24, 0xce, 0x2c, 0xc5,
	0x53, 0x70, 0x1f, 0x73, 0xc3, 0xec, 0xef, 0x34, 0x63, 0x6d, 0x68, 0xe1, 0x77, 0x7b, 0xf0, 0x6e,
	0x07, 0x7f, 0xf7, 0xa3, 0x00, 0xe2, 0xcd, 0x19, 0xf0, 0x01, 0x60, 0xeb, 0x82, 0x93, 0xc0, 0x26,
	0xc1, 0xbf, 0x63, 0x4c, 0x2f, 0xfa, 0x9f, 0x7b, 0xca, 0x7a, 0x84, 0x21, 0xec, 0x75, 0x72, 0x78,
	0x5e, 0x4f, 0x0e, 0x9a, 0x4e, 0xbd, 0xfa, 0xd7, 0x80, 0xab, 0x1e, 0xdd, 0xa8, 0x64, 0xdc, 0x3c,
	0xc7, 0xfd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x18, 0xc5, 0x33, 0xce, 0xa2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SimulationClient is the client API for Simulation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimulationClient interface {
	// Execute something on data
	SpawnAgent(ctx context.Context, in *SpawnAgentMessage, opts ...grpc.CallOption) (*SpawnAgentResultMessage, error)
	// Observe simulation
	Observe(ctx context.Context, in *ObserveRequestMessage, opts ...grpc.CallOption) (Simulation_ObserveClient, error)
}

type simulationClient struct {
	cc *grpc.ClientConn
}

func NewSimulationClient(cc *grpc.ClientConn) SimulationClient {
	return &simulationClient{cc}
}

func (c *simulationClient) SpawnAgent(ctx context.Context, in *SpawnAgentMessage, opts ...grpc.CallOption) (*SpawnAgentResultMessage, error) {
	out := new(SpawnAgentResultMessage)
	err := c.cc.Invoke(ctx, "/pb.Simulation/SpawnAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationClient) Observe(ctx context.Context, in *ObserveRequestMessage, opts ...grpc.CallOption) (Simulation_ObserveClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Simulation_serviceDesc.Streams[0], "/pb.Simulation/Observe", opts...)
	if err != nil {
		return nil, err
	}
	x := &simulationObserveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Simulation_ObserveClient interface {
	Recv() (*EntityUpdateMessage, error)
	grpc.ClientStream
}

type simulationObserveClient struct {
	grpc.ClientStream
}

func (x *simulationObserveClient) Recv() (*EntityUpdateMessage, error) {
	m := new(EntityUpdateMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SimulationServer is the server API for Simulation service.
type SimulationServer interface {
	// Execute something on data
	SpawnAgent(context.Context, *SpawnAgentMessage) (*SpawnAgentResultMessage, error)
	// Observe simulation
	Observe(*ObserveRequestMessage, Simulation_ObserveServer) error
}

func RegisterSimulationServer(s *grpc.Server, srv SimulationServer) {
	s.RegisterService(&_Simulation_serviceDesc, srv)
}

func _Simulation_SpawnAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnAgentMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServer).SpawnAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Simulation/SpawnAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServer).SpawnAgent(ctx, req.(*SpawnAgentMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simulation_Observe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ObserveRequestMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SimulationServer).Observe(m, &simulationObserveServer{stream})
}

type Simulation_ObserveServer interface {
	Send(*EntityUpdateMessage) error
	grpc.ServerStream
}

type simulationObserveServer struct {
	grpc.ServerStream
}

func (x *simulationObserveServer) Send(m *EntityUpdateMessage) error {
	return x.ServerStream.SendMsg(m)
}

var _Simulation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Simulation",
	HandlerType: (*SimulationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SpawnAgent",
			Handler:    _Simulation_SpawnAgent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Observe",
			Handler:       _Simulation_Observe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "simulation.proto",
}
