apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: environment-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: envoy-proxy-ip
    networking.gke.io/managed-certificates: environment-terrarium-ai-certificate
spec:
  backend:
    serviceName: esp-environment
    servicePort: 80