x-google-allow: all

# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

#
# Name of the service configuration.
#
name: olamai.endpoints.olamai.cloud.goog

#
# API title to appear in the user interface (Google Cloud Console).
#
title: Simulation gRPC API
apis:
  - name: olamai.endpoints.simulation.Simulation
#
# API usage restrictions.
#
usage:
  rules:
    # Spectate methods can be called without an API Key.
    - selector: olamai.endpoints.simulation.Simulation.Spectate
      allow_unregistered_calls: true
    - selector: olamai.endpoints.simulation.Simulation.SubscribeToRegion
      allow_unregistered_calls: true
    - selector: olamai.endpoints.simulation.Simulation.AgentObservation
      allow_unregistered_calls: true
    - selector: olamai.endpoints.simulation.Simulation.AgentAction
      allow_unregistered_calls: true
    - selector: olamai.endpoints.simulation.Simulation.ResetWorld
      allow_unregistered_calls: true
