# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

#
# Name of the service configuration.
#
name: olamai.endpoints.olamai.cloud.goog

#
# API title to appear in the user interface (Google Cloud Console).
#
title: Simulation gRPC API
apis:
  - name: olamai.endpoints.simulation.Simulation
#
# API usage restrictions.
#
http:
  rules:
    # Spectate methods can be called without an API Key.
    - selector: olamai.endpoints.simulation.Simulation.CreateSpectator
      post: /v1/spectators
      body: spectator
    - selector: olamai.endpoints.simulation.Simulation.SubscribeSpectator
      post: /v1/spectators/{spectator}
      body: region
    - selector: olamai.endpoints.simulation.Simulation.CreateAgent
      post: /v1/agents
      body: agent
