// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulation/simulation.proto

package olamai_endpoints_simulation

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Agent struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{1}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Agent) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Agent) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Observation struct {
	Alive                bool     `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	Cells                []string `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty"`
	Energy               int32    `protobuf:"varint,3,opt,name=energy,proto3" json:"energy,omitempty"`
	Health               int32    `protobuf:"varint,4,opt,name=health,proto3" json:"health,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Observation) Reset()         { *m = Observation{} }
func (m *Observation) String() string { return proto.CompactTextString(m) }
func (*Observation) ProtoMessage()    {}
func (*Observation) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{2}
}

func (m *Observation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Observation.Unmarshal(m, b)
}
func (m *Observation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Observation.Marshal(b, m, deterministic)
}
func (m *Observation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Observation.Merge(m, src)
}
func (m *Observation) XXX_Size() int {
	return xxx_messageInfo_Observation.Size(m)
}
func (m *Observation) XXX_DiscardUnknown() {
	xxx_messageInfo_Observation.DiscardUnknown(m)
}

var xxx_messageInfo_Observation proto.InternalMessageInfo

func (m *Observation) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

func (m *Observation) GetCells() []string {
	if m != nil {
		return m.Cells
	}
	return nil
}

func (m *Observation) GetEnergy() int32 {
	if m != nil {
		return m.Energy
	}
	return 0
}

func (m *Observation) GetHealth() int32 {
	if m != nil {
		return m.Health
	}
	return 0
}

type Action struct {
	ActionId             string   `protobuf:"bytes,1,opt,name=actionId,proto3" json:"actionId,omitempty"`
	Direction            string   `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{3}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetActionId() string {
	if m != nil {
		return m.ActionId
	}
	return ""
}

func (m *Action) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

type CellUpdate struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Occupant             string   `protobuf:"bytes,3,opt,name=occupant,proto3" json:"occupant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CellUpdate) Reset()         { *m = CellUpdate{} }
func (m *CellUpdate) String() string { return proto.CompactTextString(m) }
func (*CellUpdate) ProtoMessage()    {}
func (*CellUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{4}
}

func (m *CellUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CellUpdate.Unmarshal(m, b)
}
func (m *CellUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CellUpdate.Marshal(b, m, deterministic)
}
func (m *CellUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CellUpdate.Merge(m, src)
}
func (m *CellUpdate) XXX_Size() int {
	return xxx_messageInfo_CellUpdate.Size(m)
}
func (m *CellUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_CellUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_CellUpdate proto.InternalMessageInfo

func (m *CellUpdate) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *CellUpdate) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *CellUpdate) GetOccupant() string {
	if m != nil {
		return m.Occupant
	}
	return ""
}

type Spectator struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Spectator) Reset()         { *m = Spectator{} }
func (m *Spectator) String() string { return proto.CompactTextString(m) }
func (*Spectator) ProtoMessage()    {}
func (*Spectator) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{5}
}

func (m *Spectator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spectator.Unmarshal(m, b)
}
func (m *Spectator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spectator.Marshal(b, m, deterministic)
}
func (m *Spectator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spectator.Merge(m, src)
}
func (m *Spectator) XXX_Size() int {
	return xxx_messageInfo_Spectator.Size(m)
}
func (m *Spectator) XXX_DiscardUnknown() {
	xxx_messageInfo_Spectator.DiscardUnknown(m)
}

var xxx_messageInfo_Spectator proto.InternalMessageInfo

func (m *Spectator) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Region struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Region) Reset()         { *m = Region{} }
func (m *Region) String() string { return proto.CompactTextString(m) }
func (*Region) ProtoMessage()    {}
func (*Region) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{6}
}

func (m *Region) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Region.Unmarshal(m, b)
}
func (m *Region) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Region.Marshal(b, m, deterministic)
}
func (m *Region) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Region.Merge(m, src)
}
func (m *Region) XXX_Size() int {
	return xxx_messageInfo_Region.Size(m)
}
func (m *Region) XXX_DiscardUnknown() {
	xxx_messageInfo_Region.DiscardUnknown(m)
}

var xxx_messageInfo_Region proto.InternalMessageInfo

func (m *Region) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Region) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

// Request message for CreateShelf method.
type CreateAgentRequest struct {
	// The shelf resource to create.
	Agent                *Agent   `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAgentRequest) Reset()         { *m = CreateAgentRequest{} }
func (m *CreateAgentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAgentRequest) ProtoMessage()    {}
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{7}
}

func (m *CreateAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAgentRequest.Unmarshal(m, b)
}
func (m *CreateAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAgentRequest.Marshal(b, m, deterministic)
}
func (m *CreateAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAgentRequest.Merge(m, src)
}
func (m *CreateAgentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAgentRequest.Size(m)
}
func (m *CreateAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAgentRequest proto.InternalMessageInfo

func (m *CreateAgentRequest) GetAgent() *Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

// Request message for GetAgent method.
type GetAgentRequest struct {
	// The ID of the shelf resource to retrieve.
	Agent                string   `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAgentRequest) Reset()         { *m = GetAgentRequest{} }
func (m *GetAgentRequest) String() string { return proto.CompactTextString(m) }
func (*GetAgentRequest) ProtoMessage()    {}
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{8}
}

func (m *GetAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAgentRequest.Unmarshal(m, b)
}
func (m *GetAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAgentRequest.Marshal(b, m, deterministic)
}
func (m *GetAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAgentRequest.Merge(m, src)
}
func (m *GetAgentRequest) XXX_Size() int {
	return xxx_messageInfo_GetAgentRequest.Size(m)
}
func (m *GetAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAgentRequest proto.InternalMessageInfo

func (m *GetAgentRequest) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

// Request message for DeleteShelf method.
type DeleteAgentRequest struct {
	// The ID of the shelf to delete.
	Agent                string   `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAgentRequest) Reset()         { *m = DeleteAgentRequest{} }
func (m *DeleteAgentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAgentRequest) ProtoMessage()    {}
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{9}
}

func (m *DeleteAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAgentRequest.Unmarshal(m, b)
}
func (m *DeleteAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAgentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAgentRequest.Merge(m, src)
}
func (m *DeleteAgentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAgentRequest.Size(m)
}
func (m *DeleteAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAgentRequest proto.InternalMessageInfo

func (m *DeleteAgentRequest) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

type ActionAgentRequest struct {
	Agent                string   `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Action               *Action  `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionAgentRequest) Reset()         { *m = ActionAgentRequest{} }
func (m *ActionAgentRequest) String() string { return proto.CompactTextString(m) }
func (*ActionAgentRequest) ProtoMessage()    {}
func (*ActionAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{10}
}

func (m *ActionAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionAgentRequest.Unmarshal(m, b)
}
func (m *ActionAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionAgentRequest.Marshal(b, m, deterministic)
}
func (m *ActionAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionAgentRequest.Merge(m, src)
}
func (m *ActionAgentRequest) XXX_Size() int {
	return xxx_messageInfo_ActionAgentRequest.Size(m)
}
func (m *ActionAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActionAgentRequest proto.InternalMessageInfo

func (m *ActionAgentRequest) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

func (m *ActionAgentRequest) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

// Request message for GetAgent method.
type GetObservationRequest struct {
	// The ID of the shelf resource to retrieve.
	Agent                string   `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObservationRequest) Reset()         { *m = GetObservationRequest{} }
func (m *GetObservationRequest) String() string { return proto.CompactTextString(m) }
func (*GetObservationRequest) ProtoMessage()    {}
func (*GetObservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{11}
}

func (m *GetObservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObservationRequest.Unmarshal(m, b)
}
func (m *GetObservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObservationRequest.Marshal(b, m, deterministic)
}
func (m *GetObservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObservationRequest.Merge(m, src)
}
func (m *GetObservationRequest) XXX_Size() int {
	return xxx_messageInfo_GetObservationRequest.Size(m)
}
func (m *GetObservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetObservationRequest proto.InternalMessageInfo

func (m *GetObservationRequest) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

type CreateSpectatorRequest struct {
	Spectator            *Spectator `protobuf:"bytes,1,opt,name=spectator,proto3" json:"spectator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateSpectatorRequest) Reset()         { *m = CreateSpectatorRequest{} }
func (m *CreateSpectatorRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSpectatorRequest) ProtoMessage()    {}
func (*CreateSpectatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{12}
}

func (m *CreateSpectatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSpectatorRequest.Unmarshal(m, b)
}
func (m *CreateSpectatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSpectatorRequest.Marshal(b, m, deterministic)
}
func (m *CreateSpectatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSpectatorRequest.Merge(m, src)
}
func (m *CreateSpectatorRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSpectatorRequest.Size(m)
}
func (m *CreateSpectatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSpectatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSpectatorRequest proto.InternalMessageInfo

func (m *CreateSpectatorRequest) GetSpectator() *Spectator {
	if m != nil {
		return m.Spectator
	}
	return nil
}

type SubscribeSpectatorRequest struct {
	Spectator            string   `protobuf:"bytes,1,opt,name=spectator,proto3" json:"spectator,omitempty"`
	Region               *Region  `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeSpectatorRequest) Reset()         { *m = SubscribeSpectatorRequest{} }
func (m *SubscribeSpectatorRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeSpectatorRequest) ProtoMessage()    {}
func (*SubscribeSpectatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{13}
}

func (m *SubscribeSpectatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeSpectatorRequest.Unmarshal(m, b)
}
func (m *SubscribeSpectatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeSpectatorRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeSpectatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeSpectatorRequest.Merge(m, src)
}
func (m *SubscribeSpectatorRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeSpectatorRequest.Size(m)
}
func (m *SubscribeSpectatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeSpectatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeSpectatorRequest proto.InternalMessageInfo

func (m *SubscribeSpectatorRequest) GetSpectator() string {
	if m != nil {
		return m.Spectator
	}
	return ""
}

func (m *SubscribeSpectatorRequest) GetRegion() *Region {
	if m != nil {
		return m.Region
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "olamai.endpoints.simulation.Empty")
	proto.RegisterType((*Agent)(nil), "olamai.endpoints.simulation.Agent")
	proto.RegisterType((*Observation)(nil), "olamai.endpoints.simulation.Observation")
	proto.RegisterType((*Action)(nil), "olamai.endpoints.simulation.Action")
	proto.RegisterType((*CellUpdate)(nil), "olamai.endpoints.simulation.CellUpdate")
	proto.RegisterType((*Spectator)(nil), "olamai.endpoints.simulation.Spectator")
	proto.RegisterType((*Region)(nil), "olamai.endpoints.simulation.Region")
	proto.RegisterType((*CreateAgentRequest)(nil), "olamai.endpoints.simulation.CreateAgentRequest")
	proto.RegisterType((*GetAgentRequest)(nil), "olamai.endpoints.simulation.GetAgentRequest")
	proto.RegisterType((*DeleteAgentRequest)(nil), "olamai.endpoints.simulation.DeleteAgentRequest")
	proto.RegisterType((*ActionAgentRequest)(nil), "olamai.endpoints.simulation.ActionAgentRequest")
	proto.RegisterType((*GetObservationRequest)(nil), "olamai.endpoints.simulation.GetObservationRequest")
	proto.RegisterType((*CreateSpectatorRequest)(nil), "olamai.endpoints.simulation.CreateSpectatorRequest")
	proto.RegisterType((*SubscribeSpectatorRequest)(nil), "olamai.endpoints.simulation.SubscribeSpectatorRequest")
}

func init() { proto.RegisterFile("simulation/simulation.proto", fileDescriptor_17e12b66aec6c312) }

var fileDescriptor_17e12b66aec6c312 = []byte{
	// 685 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x96, 0xd3, 0x5f, 0xf2, 0x8b, 0xc7, 0xa8, 0x55, 0x87, 0x52, 0xa5, 0x4e, 0x0f, 0x61, 0xa9,
	0x68, 0x14, 0x41, 0x02, 0xa9, 0x84, 0x50, 0x38, 0x95, 0x16, 0x55, 0x5c, 0x40, 0x72, 0x85, 0xb8,
	0x21, 0x6d, 0xec, 0x55, 0x6a, 0xc9, 0xb5, 0x8d, 0xbd, 0x09, 0x8d, 0xaa, 0x72, 0xe0, 0xc0, 0x19,
	0x09, 0x8e, 0x3c, 0x0c, 0xef, 0xc0, 0x2b, 0xf0, 0x20, 0xc8, 0xbb, 0xfe, 0x17, 0xbb, 0x38, 0x3e,
	0x75, 0x67, 0x33, 0x33, 0xdf, 0xb7, 0x33, 0xdf, 0xe7, 0x42, 0x37, 0xb4, 0x2f, 0xe7, 0x0e, 0xe5,
	0xb6, 0xe7, 0x8e, 0xb2, 0xe3, 0xd0, 0x0f, 0x3c, 0xee, 0x61, 0xd7, 0x73, 0xe8, 0x25, 0xb5, 0x87,
	0xcc, 0xb5, 0x7c, 0xcf, 0x76, 0x79, 0x38, 0xcc, 0x52, 0xf4, 0x6d, 0xea, 0xba, 0x1e, 0x17, 0xe7,
	0x50, 0xe6, 0x93, 0xff, 0xa1, 0xf9, 0xea, 0xd2, 0xe7, 0x4b, 0x72, 0x04, 0xcd, 0xe3, 0x19, 0x73,
	0x39, 0x6e, 0x42, 0xc3, 0xb6, 0x3a, 0x4a, 0x4f, 0xe9, 0xab, 0x46, 0xc3, 0xb6, 0xf0, 0x0e, 0x28,
	0x57, 0x9d, 0x46, 0x4f, 0xe9, 0x37, 0x0d, 0xe5, 0x2a, 0x8a, 0x96, 0x9d, 0x0d, 0x19, 0x2d, 0x89,
	0x0d, 0xda, 0xdb, 0x69, 0xc8, 0x82, 0x85, 0xe8, 0x89, 0x3b, 0xd0, 0xa4, 0x8e, 0xbd, 0x60, 0xa2,
	0xba, 0x6d, 0xc8, 0x20, 0xba, 0x35, 0x99, 0xe3, 0x84, 0x9d, 0x46, 0x6f, 0xa3, 0xaf, 0x1a, 0x32,
	0xc0, 0x5d, 0x68, 0x31, 0x97, 0x05, 0xb3, 0xa4, 0x5b, 0x1c, 0x45, 0xf7, 0x17, 0x8c, 0x3a, 0xfc,
	0xa2, 0xf3, 0x9f, 0xbc, 0x97, 0x11, 0x79, 0x09, 0xad, 0x63, 0x53, 0xa0, 0xe8, 0xd0, 0xa6, 0xe2,
	0xf4, 0x3a, 0xa1, 0x99, 0xc6, 0xb8, 0x0f, 0xaa, 0x65, 0x07, 0x4c, 0x84, 0x82, 0xb4, 0x6a, 0x64,
	0x17, 0xe4, 0x14, 0xe0, 0x84, 0x39, 0xce, 0x3b, 0xdf, 0xa2, 0x9c, 0xc9, 0x87, 0x29, 0x2b, 0x0f,
	0x8b, 0x9f, 0xb9, 0x8c, 0x30, 0x3c, 0xd3, 0x9c, 0xfb, 0xd4, 0xe5, 0x82, 0x9f, 0x6a, 0xa4, 0x31,
	0xe9, 0x82, 0x7a, 0xee, 0x33, 0x93, 0x53, 0xee, 0x05, 0xc5, 0x69, 0x91, 0x03, 0x68, 0x19, 0x6c,
	0x16, 0xd1, 0xac, 0x68, 0x4f, 0xde, 0x00, 0x9e, 0x04, 0x8c, 0x72, 0x26, 0x46, 0x6e, 0xb0, 0x8f,
	0x73, 0x16, 0x72, 0x7c, 0x0e, 0x4d, 0x1a, 0xc5, 0xa2, 0x4a, 0x1b, 0x93, 0x61, 0xc5, 0x2e, 0x87,
	0xb2, 0x52, 0x16, 0x90, 0x43, 0xd8, 0x3a, 0x63, 0x7c, 0xa5, 0xd9, 0x4e, 0xbe, 0x99, 0x9a, 0x24,
	0x0e, 0x00, 0x4f, 0x99, 0xc3, 0x0a, 0xc0, 0xb7, 0xe7, 0xce, 0x00, 0xe5, 0xc4, 0xd7, 0xe7, 0xe2,
	0x0b, 0x68, 0xd1, 0x6c, 0xe8, 0xda, 0xf8, 0x41, 0x35, 0x77, 0x91, 0x6a, 0xc4, 0x25, 0xe4, 0x31,
	0xdc, 0x3b, 0x63, 0x3c, 0x27, 0xa4, 0x6a, 0x5e, 0x1f, 0x60, 0x57, 0x0e, 0x2f, 0xdd, 0x42, 0x92,
	0x7f, 0x0a, 0x6a, 0x98, 0xdc, 0xc5, 0x43, 0x7c, 0x58, 0x49, 0x24, 0xeb, 0x90, 0x15, 0x92, 0x05,
	0xec, 0x9d, 0xcf, 0xa7, 0xa1, 0x19, 0xd8, 0xd3, 0x32, 0xc4, 0x7e, 0x11, 0x42, 0xcd, 0x95, 0x46,
	0x63, 0x08, 0xc4, 0xf6, 0x6b, 0x8d, 0x41, 0x0a, 0xc5, 0x88, 0x4b, 0xc6, 0xbf, 0xda, 0x00, 0xe7,
	0xe9, 0xaf, 0x78, 0x03, 0x5a, 0x4e, 0x23, 0x38, 0xaa, 0x6c, 0x55, 0x56, 0x93, 0x5e, 0x43, 0x3e,
	0x64, 0xef, 0xcb, 0xef, 0x3f, 0xdf, 0x1b, 0x77, 0x09, 0x8c, 0x16, 0x4f, 0x47, 0x62, 0xba, 0xe1,
	0x24, 0xde, 0xe8, 0x15, 0xb4, 0x13, 0x49, 0xe1, 0xa3, 0xca, 0x56, 0x05, 0xe5, 0xd5, 0x02, 0xd6,
	0x05, 0xf0, 0x0e, 0x62, 0x06, 0x3c, 0xba, 0x16, 0x7f, 0x6f, 0xf0, 0x33, 0x68, 0x39, 0x8d, 0xae,
	0x79, 0x78, 0x59, 0xcd, 0x6b, 0xf0, 0xe5, 0xd7, 0x2e, 0xc6, 0x1f, 0xdc, 0x86, 0xff, 0x55, 0x01,
	0x2d, 0x27, 0xfc, 0x35, 0x04, 0xca, 0x16, 0xa9, 0x45, 0x80, 0x08, 0x02, 0xfb, 0xe4, 0x16, 0x02,
	0x93, 0xd8, 0x17, 0xf8, 0x4d, 0x81, 0xcd, 0x55, 0x63, 0xe0, 0x78, 0xdd, 0x26, 0xca, 0x2e, 0xd2,
	0xfb, 0x95, 0x35, 0xb9, 0x02, 0xd2, 0x13, 0xa4, 0x74, 0xec, 0x44, 0xa4, 0xbc, 0xec, 0x87, 0x6c,
	0x36, 0x3f, 0x14, 0xd8, 0x2a, 0x98, 0x0f, 0x8f, 0x6a, 0x28, 0xb3, 0xe8, 0x23, 0xfd, 0xb0, 0xba,
	0x28, 0xfd, 0x4a, 0x93, 0xfb, 0x82, 0x53, 0x97, 0x6c, 0x46, 0x9c, 0x52, 0xa7, 0x85, 0x93, 0xcc,
	0x75, 0x4f, 0x14, 0xfc, 0xa9, 0x00, 0x96, 0x3d, 0x8b, 0xcf, 0xaa, 0xcd, 0xff, 0x2f, 0x93, 0xd7,
	0x5a, 0xe0, 0x40, 0xf0, 0x3a, 0x20, 0xfa, 0x2a, 0xaf, 0xd1, 0x75, 0x7a, 0xbe, 0x99, 0xc4, 0xce,
	0xc6, 0x19, 0x80, 0xc1, 0x42, 0xc6, 0xdf, 0x7b, 0x81, 0x63, 0x61, 0x8d, 0xee, 0xb5, 0x18, 0x6c,
	0x0b, 0x06, 0xda, 0x40, 0x8d, 0x18, 0x7c, 0x8a, 0x5a, 0x4f, 0x5b, 0xe2, 0x9f, 0xfa, 0xd1, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x33, 0x75, 0xa5, 0x1d, 0x23, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SimulationClient is the client API for Simulation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimulationClient interface {
	// Creates a new agent
	CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	// Returns a specific agent
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	// Deletes an agent
	DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*Empty, error)
	// Perform agent action
	ActionAgent(ctx context.Context, in *ActionAgentRequest, opts ...grpc.CallOption) (*Empty, error)
	// Returns a specific book.
	GetObservation(ctx context.Context, in *GetObservationRequest, opts ...grpc.CallOption) (*Observation, error)
	// Start a spectation stream
	CreateSpectator(ctx context.Context, in *CreateSpectatorRequest, opts ...grpc.CallOption) (Simulation_CreateSpectatorClient, error)
	// Subscribe a spectator to a region
	SubscribeSpectator(ctx context.Context, in *SubscribeSpectatorRequest, opts ...grpc.CallOption) (*Empty, error)
	// Reset the world
	ResetWorld(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type simulationClient struct {
	cc *grpc.ClientConn
}

func NewSimulationClient(cc *grpc.ClientConn) SimulationClient {
	return &simulationClient{cc}
}

func (c *simulationClient) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	out := new(Agent)
	err := c.cc.Invoke(ctx, "/olamai.endpoints.simulation.Simulation/CreateAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	out := new(Agent)
	err := c.cc.Invoke(ctx, "/olamai.endpoints.simulation.Simulation/GetAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationClient) DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/olamai.endpoints.simulation.Simulation/DeleteAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationClient) ActionAgent(ctx context.Context, in *ActionAgentRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/olamai.endpoints.simulation.Simulation/ActionAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationClient) GetObservation(ctx context.Context, in *GetObservationRequest, opts ...grpc.CallOption) (*Observation, error) {
	out := new(Observation)
	err := c.cc.Invoke(ctx, "/olamai.endpoints.simulation.Simulation/GetObservation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationClient) CreateSpectator(ctx context.Context, in *CreateSpectatorRequest, opts ...grpc.CallOption) (Simulation_CreateSpectatorClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Simulation_serviceDesc.Streams[0], "/olamai.endpoints.simulation.Simulation/CreateSpectator", opts...)
	if err != nil {
		return nil, err
	}
	x := &simulationCreateSpectatorClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Simulation_CreateSpectatorClient interface {
	Recv() (*CellUpdate, error)
	grpc.ClientStream
}

type simulationCreateSpectatorClient struct {
	grpc.ClientStream
}

func (x *simulationCreateSpectatorClient) Recv() (*CellUpdate, error) {
	m := new(CellUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *simulationClient) SubscribeSpectator(ctx context.Context, in *SubscribeSpectatorRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/olamai.endpoints.simulation.Simulation/SubscribeSpectator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationClient) ResetWorld(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/olamai.endpoints.simulation.Simulation/ResetWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimulationServer is the server API for Simulation service.
type SimulationServer interface {
	// Creates a new agent
	CreateAgent(context.Context, *CreateAgentRequest) (*Agent, error)
	// Returns a specific agent
	GetAgent(context.Context, *GetAgentRequest) (*Agent, error)
	// Deletes an agent
	DeleteAgent(context.Context, *DeleteAgentRequest) (*Empty, error)
	// Perform agent action
	ActionAgent(context.Context, *ActionAgentRequest) (*Empty, error)
	// Returns a specific book.
	GetObservation(context.Context, *GetObservationRequest) (*Observation, error)
	// Start a spectation stream
	CreateSpectator(*CreateSpectatorRequest, Simulation_CreateSpectatorServer) error
	// Subscribe a spectator to a region
	SubscribeSpectator(context.Context, *SubscribeSpectatorRequest) (*Empty, error)
	// Reset the world
	ResetWorld(context.Context, *Empty) (*Empty, error)
}

func RegisterSimulationServer(s *grpc.Server, srv SimulationServer) {
	s.RegisterService(&_Simulation_serviceDesc, srv)
}

func _Simulation_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/olamai.endpoints.simulation.Simulation/CreateAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServer).CreateAgent(ctx, req.(*CreateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simulation_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/olamai.endpoints.simulation.Simulation/GetAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simulation_DeleteAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServer).DeleteAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/olamai.endpoints.simulation.Simulation/DeleteAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServer).DeleteAgent(ctx, req.(*DeleteAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simulation_ActionAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServer).ActionAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/olamai.endpoints.simulation.Simulation/ActionAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServer).ActionAgent(ctx, req.(*ActionAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simulation_GetObservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServer).GetObservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/olamai.endpoints.simulation.Simulation/GetObservation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServer).GetObservation(ctx, req.(*GetObservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simulation_CreateSpectator_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateSpectatorRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SimulationServer).CreateSpectator(m, &simulationCreateSpectatorServer{stream})
}

type Simulation_CreateSpectatorServer interface {
	Send(*CellUpdate) error
	grpc.ServerStream
}

type simulationCreateSpectatorServer struct {
	grpc.ServerStream
}

func (x *simulationCreateSpectatorServer) Send(m *CellUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _Simulation_SubscribeSpectator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeSpectatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServer).SubscribeSpectator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/olamai.endpoints.simulation.Simulation/SubscribeSpectator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServer).SubscribeSpectator(ctx, req.(*SubscribeSpectatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simulation_ResetWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServer).ResetWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/olamai.endpoints.simulation.Simulation/ResetWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServer).ResetWorld(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Simulation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "olamai.endpoints.simulation.Simulation",
	HandlerType: (*SimulationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgent",
			Handler:    _Simulation_CreateAgent_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _Simulation_GetAgent_Handler,
		},
		{
			MethodName: "DeleteAgent",
			Handler:    _Simulation_DeleteAgent_Handler,
		},
		{
			MethodName: "ActionAgent",
			Handler:    _Simulation_ActionAgent_Handler,
		},
		{
			MethodName: "GetObservation",
			Handler:    _Simulation_GetObservation_Handler,
		},
		{
			MethodName: "SubscribeSpectator",
			Handler:    _Simulation_SubscribeSpectator_Handler,
		},
		{
			MethodName: "ResetWorld",
			Handler:    _Simulation_ResetWorld_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateSpectator",
			Handler:       _Simulation_CreateSpectator_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "simulation/simulation.proto",
}
